config/routes.rb
Rails.application.routes.draw do

resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:new, :create]
  end

  root 'home#index'
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews
  validates :name, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip_code, presence: true

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant
  validates :rating, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @restaurants = Restaurant.limit(10)
  end



  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :city, :state,
      :zip_code, :description, :category)
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      flash[:notice] = "Success!"
      redirect_to '/restaurants'
    else
      flash.now[:notice] = "Your restaurant couldn't be saved."
      render :new
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :city, :state,
      :zip_code, :description, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @restaurants = Restaurant.all
    @reviews = Review.all
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end


  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.build(review_params)

    if @review.save
      flash[:notice] = "Success!"
      redirect_to @restaurant
    else
      flash[:notice] = "Your review couldnt be saved."
      redirect_to @restaurant
    end
  end



  private
    def review_params
      params.require(:review).permit(:rating, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h3>List of 10 recently added restaurants</h3>

  <ul>
  <% @restaurants.each do |restaurant| %>
      <li><%= link_to restaurant.name, restaurant_path(restaurant) %>, <%= "#{restaurant.city} (#{restaurant.state})" %></li>
  <% end %>
  </ul>


  <%= link_to "All Restaurants", restaurants_path, :class => "button"  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoodEats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurants/index.html.erb
<h3>All Restaurants</h3>

  <ul>
  <% @restaurants.each do |restaurant| %>
      <li><%= link_to restaurant.name, restaurant_path(restaurant) %>, <%= "#{restaurant.city} (#{restaurant.state})" %></li>
  <% end %>
  </ul>


  <%= link_to "Add New Resaurnt", new_restaurant_path, :class => "button"  %>

app/views/restaurants/new.html.erb
<h3>Add A New Restaurant</h3>

<%= form_for @restaurant do |f| %>

  <% if @restaurant.errors.any? %>
    <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div>
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div>
    <%= f.label :zip_code %>
    <%= f.number_field :zip_code %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description, :rows => 4, :cols => 50  %>
  </div>

</br>

<div>
  <%= f.label :category %>
  <%= f.select :category, ['Thai','Chinese','Japanese','Indian','Pakistani', 'American', 'Italian', 'French', 'Irish', 'German', 'Polish', 'Russian', 'Cuban', 'Mexican', 'Latin', 'Fusion', 'Cajun'] %>
</div>

</br>

   <%= f.submit 'Submit' %>
<% end %>
<hr>

<%= link_to 'Back', :back %>

app/views/restaurants/show.html.erb
<h3><%= @restaurant.name %></h3>

<ul>
  <li>Address: <%= @restaurant.address %></li>
  <li>City: <%= @restaurant.city %></li>
  <li>State: <%= @restaurant.state %></li>
  <li>ZipCode: <%= @restaurant.zip_code %></li>
  <li>Description: <%= @restaurant.description %></li>
  <li>Category: <%= @restaurant.category %></li>
</ul>


<%= link_to "Add a Review", new_restaurant_review_path(@restaurant, @review), :class => "button"  %>

<h3>Customer Reviews</h3>

<ul>

<% @restaurant.reviews.each do |review| %>
<li>Rating:<%= review.rating %></li>
<li>Review: <%= review.body %></li>
<li>Date: <%= time_ago_in_words(review.created_at) %> ago </li>

</br>
<hr>

<% end %>

</ul>

<hr>

<%= link_to 'Back', restaurants_path %>

app/views/reviews/new.html.erb
<h3>Add A Review</h3>

<%= form_for([@restaurant, @restaurant.reviews.build]) do |f| %>

<div>
  <%= f.label :rating %>
  <%= f.select :rating, ['1','2','3','4','5'] %>
</div>
</br>

<div>
  <%= f.label :body %>
  <%= f.text_area :body, :rows => 4, :cols => 50 %>
</div>
</br>


<%= f.submit 'Submit' %>
<% end %>
<hr>

<%= link_to "Back to Restaurants", restaurant_path(@restaurant, @review), :class => "button"  %>